name: Deploy main branch

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

          # NOTE: .GitInfo や .Lastmod を使う場合には以下のオプションを有効にすること
          # fetch-depth: 0

      - name: Install Hugo
        uses: ./.github/actions/install_hugo

      - name: Build pages
        run: hugo -v

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
